export const GET_BOARDLIST_REQUEST = 'GET_BOARDLIST_REQUEST'
export const GET_BOARDLIST_SUCCESS = 'GET_BOARDLIST_SUCCESS'
export const GET_BOARDLIST_FAILURE = 'GET_BOARDLIST_FAILURE'

export const INSERT_BOARD_REQUEST = 'INSERT_BOARD_REQUEST'
export const INSERT_BOARD_SUCCESS = 'INSERT_BOARD_SUCCESS'
export const INSERT_BOARD_FAILURE = 'INSERT_BOARD_FAILURE'

export const UPDATE_BOARD_REQUEST = 'UPDATE_BOARD_REQUEST'
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS'
export const UPDATE_BOARD_FAILURE = 'UPDATE_BOARD_FAILURE'

export const DELETE_BOARD_REQUEST = 'DELETE_BOARD_REQUEST'
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS'
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE'
